execfile('monty.sol')
t = tokenizer.new(io.open('/tmp/monty', io.MODE_READ))
ttg = ttreegen.new(t)
p = parser.new(ttg)
c = converter.new(p)
stmt = c:run()
print('Resulting statement:')
ast.print(stmt)
print('---Running results begin here---')
stmt()
